services:
  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  _defaults:
    autowire: true
    autoconfigure: true

  Akyos\UXExportBundle\:
    resource: '../src/*'

  Akyos\UXExportBundle\Controller\:
    resource: '../src/Controller/*'
    autowire: true
    autoconfigure: true
